# src/components/state_management.py
from typing import List, Optional, TypedDict, Dict
from langchain.schema import BaseMessage, Document

# Define the state structure for the LangGraph
class State(TypedDict):
    """
    Defines the state structure for the LangGraph application.

    This TypedDict specifies the keys and types of data that will be passed
    between nodes in the graph. It includes the conversation history,
    intermediate search results, parsed documents, retrieved context,
    and the final response.
    """
    # List of messages representing the conversation history (HumanMessage, AIMessage, etc.)
    messages: List[BaseMessage]

    # Raw search results from the web search
    web_results: Optional[List[Dict[str, str]]]

    # Parsed documents fetched from search result URLs
    retrieved_docs: Optional[List[Document]]

    # Chunks of text retrieved from the vector store based on the query
    context_chunks: Optional[List[Document]]

    # The final response generated by the LLM
    response: Optional[str]

    # Flag to indicate if the process should continue or terminate early
    should_continue: bool